// Code generated by "stringer -type=messageType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[textMessage-0]
	_ = x[animationMessage-1]
	_ = x[audioMessage-2]
	_ = x[documentMessage-3]
	_ = x[photoMessage-4]
	_ = x[stickerMessage-5]
	_ = x[videoMessage-6]
	_ = x[videoNoteMessage-7]
	_ = x[voiceMessage-8]
	_ = x[fileUploadMessage-9]
	_ = x[directoryMessage-10]
}

const _messageType_name = "textMessageanimationMessageaudioMessagedocumentMessagephotoMessagestickerMessagevideoMessagevideoNoteMessagevoiceMessagefileUploadMessagefolderMessage"

var _messageType_index = [...]uint8{0, 11, 27, 39, 54, 66, 80, 92, 108, 120, 137, 150}

func (i messageType) String() string {
	if i < 0 || i >= messageType(len(_messageType_index)-1) {
		return "messageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _messageType_name[_messageType_index[i]:_messageType_index[i+1]]
}
